import Head from 'next/head';
import { gql } from '@apollo/client';

import styles from '../styles/Home.module.css';
import client from '../apollo-client';
import Card from '../components/Card';

interface People {
  name: string
  birthYear: string
  gender: string
  eyeColor: string
  hairColor: string
  homeworld: {
    name: string
    population: number
    diameter: number
  }
};

export default function Home({ people }: {
  people: People[]
}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://unpkg.com/@themesberg/flowbite@latest/dist/flowbite.bundle.js"></script>
      </Head>

      <div className="container m-auto p-4">
        <div className="flex justify-center flex-wrap">
          {
            people.map((ele, index) => <Card people={ele} key={index} />)
          }
        </div>
      </div>
    </div>
  );
}

const GET_ALL_PEOPLE = gql`
  query AllPeople($first: Int) {
    allPeople(first: $first) {
      totalCount
      pageInfo {
        endCursor
        hasNextPage
        hasPreviousPage
        startCursor
      }
      people {
        id
        hairColor
        eyeColor
        birthYear
        homeworld {
          population
          diameter
          name
        }
        name
        gender
      }
    }
  }
`;

export async function getServerSideProps() {
  const { data } = await client.query({
    query: GET_ALL_PEOPLE,
    variables: {
      first: 10
    }
  });

  return {
    props: {
      people: data.allPeople.people,
    },
  };
}
